export const images = {
  logo: '../images/prydan-removebg-preview.png',
  iconClose: '../images/icon-close.svg',
  banner:'../images/banner-img.png',

  iconFacebook: '../images/facebook.svg',
  iconFacebookHvr: '../images/facebook-hvr.svg',
  iconLinkedin: '../images/linkedin.svg',
  iconLinkedinHvr: '../images/linkedin-hvr.svg',
  iconTwitter:  '../images/twitter.svg',
  iconTwitterHvr: '../images/twitter-hvr.svg',


  contactAmit: '../images/amit-kumar-trivedi-220x220.png',
  contactAmit2x: '../images/amit-kumar-trivedi-220x220.png',

  serCustom: '../images/ser-custom-software.svg',
  serUiux: '../images/ser-ui-ux-design-services.svg',
  serProduct: '../images/ser-product-development-services.svg',
  serEnterprise: '../images/cser-enterprise-mobile-application-development.svg',
  serEcommerce: '../images/ser-ecommerce.svg',
  serDedicated: '../images/ser-dedicated-software.svg',
  serWebapp: '../images/ser-custom-web-app-development.svg',
  serTesting: '../images/ser-software-testing.svg',
  serAppdev: '../images/ser-application-development-services.svg',
  serApi: '../images/ser-api-integration-services.svg',
  serHire: '../images/ser-hire-dedicated-software.svg',


  iconGo: '../images/Go.svg',
  iconPython: '../images/Python.svg',
  iconRubyOnRails: '../images/RubyOnRails.svg',
  iconAspNET: '../images/AspNET.svg',
  iconNETCore: '../images/NETCore.svg',
  iconPHP: '../images/PHP.svg',
  iconNodeJS: '../images/NodeJS.svg',
  iconJava: '../images/Java.svg',
  iconElectron: '../images/Electron.svg',
  iconFlutter: '../images/Flutter.svg',
  iconTypeScript: '../images/TypeScript.svg',
  iconXamarin: '../images/Xamarin.svg',
  iconVue: '../images/Vue.svg',
  iconReact: '../images/React.svg',
  iconReactNative: '../images/ReactNative.svg',
  iconWPF: '../images/WPF.svg',
  iconAdnroid: '../images/Adnroid.svg',
  iconJavaScript: '../images/JavaScript.svg',
  iconAngularJS: '../images/AngularJS.svg',
  iconiOS: '../images/iOS.svg',
  iconUnity: '../images/Unity.svg',
  iconSQLServer: '../images/SQLServer.svg',
  iconGroup32: '../images/Group 32.svg',
  iconCloudera: '../images/Cloudera.svg',
  iconGroup42: '../images/CosmosDB.svg',
  iconMySQL: '../images/MySQL.svg',
  iconRethinkDB: '../images/RethinkDB.svg',
  iconFirestore: '../images/Firestore.svg',
  iconPostageSQL: '../images/PostageSQL.svg',
  iconOracle: '../images/Oracle.svg',
  iconhbase: '../images/hbase.svg',
  iconMAPR: '../images/MAPR.svg',
  iconHortonworks: '../images/Hortonworks.svg',
  iconHadoop: '../images/Hadoop.svg',
  iconFirebase: '../images/Firebase.svg',
  iconCouchbase: '../images/Couchbase.svg',
  iconNeptune: '../images/Neptune.svg',
  iconRedis: '../images/Redis.svg',
  iconMongoDB: '../images/MongoDB.svg',
  iconcassandra: '../images/cassandra.svg',
  iconElasticSearch: '../images/ElasticSearch.svg',
  iconSuccessfactors: '../images/Successfactors.svg',
  iconWordpress: '../images/Wordpress.svg',
  iconMagento: '../images/Magento.svg',
  iconCanvas: '../images/Canvas.svg',
  iconLitmus: '../images/Litmus.svg',
  iconLiferay: '../images/Liferay.svg',
  iconShopify: '../images/Shopify.svg',
  iconDocebo: '../images/Docebo.svg',
  iconMoodle: '../images/Moodle.svg',
  iconUmbraco: '../images/Umbraco.svg',
  iconSitecore: '../images/Sitecore.svg',
  iconTotara: '../images/Totara.svg',
  iconAdapt: '../images/Adapt.svg',
  iconGooglecloud: '../images/Google cloud.svg',
  icontwilio: '../images/twilio.svg',
  iconAlgolia: '../images/Algolia.svg',
  iconTalend: '../images/Talend.svg',
  iconSpluck: '../images/Spluck.svg',
  iconAWS: '../images/AWS.svg',
  iconAlfresco: '../images/Alfresco.svg',
  iconStripe: '../images/Stripe.svg',
  iconSharePoint: '../images/SharePoint.svg',
  iconApigee: '../images/Apigee.svg',
  iconPivotal: '../images/Pivotal.svg',
  iconSalesforce: '../images/Salesforce.svg',
  iconDocker: '../images/Docker.svg',
  iconMulesoft: '../images/Mulesoft.svg',
  iconNexmo: '../images/Nexmo.svg',
  iconkubernetes: '../images/kubernetes.svg',
  iconAzure: '../images/Azure.svg',
  iconSoupUI: '../images/SoupUI.svg',
  iconMochas: '../images/Mochas.svg',
  iconAppium: '../images/Appium.svg',
  iconHoverfly: '../images/Hoverfly.svg',
  iconJMeter: '../images/JMeter.svg',
  iconKatalon: '../images/Katalon.svg',
  iconSelenium: '../images/Selenium.svg',
  iconGatling: '../images/Gatling.svg',
  iconSaucelabs: '../images/Saucelabs.svg',
  iconTravisCI: '../images/TravisCI.svg',
  iconCircleCI: '../images/CircleCI.svg',
  iconCodeship: '../images/Codeship.svg',
  icongradle: '../images/gradle.svg',
  iconJenkins: '../images/Jenkins.svg',
  iconCodeigniter: '../images/Codeigniter.svg',
  iconLaravel: '../images/Laravel.svg',
  iconZend: '../images/zend-framework.svg',
  iconYii: '../images/yii_logo_dark.svg',

  faqDownArrow: '../images/faq-down-arrow.svg',
  footermap: '../images/map.png',
  purplenotesResultScreen2x: '../images/yii_logo_dark.svg',
  purplenotesResultScreen: '../images/yii_logo_dark.svg',
  caseImg1: '../images/yii_logo_dark.svg',
  bannerImage: '../images/yii_logo_dark.svg',
  
  purplenotesAppScreen1:  '../images/yii_logo_dark.svg',
  purplenotesAppScreen2: '../images/yii_logo_dark.svg',
  purplenotesAppScreen3: '../images/yii_logo_dark.svg',
  purplenotesAppScreen4: '../images/yii_logo_dark.svg',
  purplenotesAppScreen5: '../images/yii_logo_dark.svg',
  purplenotesAppScreen6: '../images/yii_logo_dark.svg',
  purplenotesAppScreen7: '../images/yii_logo_dark.svg',
  purplenotesAppScreen8: '../images/yii_logo_dark.svg',

}
